stages:
  - build
  
before_script:
  - set -euxo pipefail

build-war:
  image: privacybydesign/jdk8:latest
  stage: build
  script:
    - mkdir artifacts
    - gradle clean
    - gradle build
    - mv build/libs/irma_idin_server.war ./irma_idin_server.war
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - irma_idin_server.war
